# Generated by Django 4.0.3 on 2024-02-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INDICATOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ('year',),
            },
        ),
    ]
